"use client";

export const FILTERS = [
  { id: "all",          label: "All Experts",         icon: "⚡" },
  { id: "ai",           label: "AI",                  icon: "🤖" },
  { id: "goal",         label: "Goal-Based",          icon: "🎯" },
  { id: "communication",label: "Communication",       icon: "💬" },
  { id: "data",         label: "Data Science",        icon: "📊" },
  { id: "leadership",   label: "Leadership",          icon: "🚀" },
  { id: "management",   label: "Management",          icon: "🗂️" },
  { id: "softskills",   label: "Soft Skills",         icon: "🌟" },
  { id: "technical",    label: "Technical",           icon: "🔧" },
  { id: "wellness",     label: "Wellness",            icon: "🧘" },
];

export const CAT_COLORS = {
  ai:            { color: "#7c3aed", avatarBg: "#f5f3ff", avatarColor: "#7c3aed", pill: "#7c3aed", bg: "#f5f3ff", text: "#7c3aed", border: "#ddd6fe" },
  goal:          { color: "#2563eb", avatarBg: "#eff6ff", avatarColor: "#2563eb", pill: "#2563eb", bg: "#eff6ff", text: "#2563eb", border: "#bfdbfe" },
  communication: { color: "#0891b2", avatarBg: "#ecfeff", avatarColor: "#0891b2", pill: "#0891b2", bg: "#ecfeff", text: "#0891b2", border: "#a5f3fc" },
  data:          { color: "#1a9e60", avatarBg: "#ecfdf5", avatarColor: "#1a9e60", pill: "#1a9e60", bg: "#ecfdf5", text: "#1a9e60", border: "#a7f3d0" },
  leadership:    { color: "#e05a00", avatarBg: "#fff7ed", avatarColor: "#e05a00", pill: "#e05a00", bg: "#fff7ed", text: "#e05a00", border: "#fed7aa" },
  management:    { color: "#d97706", avatarBg: "#fffbeb", avatarColor: "#d97706", pill: "#d97706", bg: "#fffbeb", text: "#d97706", border: "#fde68a" },
  softskills:    { color: "#db2777", avatarBg: "#fdf2f8", avatarColor: "#db2777", pill: "#db2777", bg: "#fdf2f8", text: "#db2777", border: "#fbcfe8" },
  technical:     { color: "#0f766e", avatarBg: "#f0fdfa", avatarColor: "#0f766e", pill: "#0f766e", bg: "#f0fdfa", text: "#0f766e", border: "#99f6e4" },
  wellness:      { color: "#65a30d", avatarBg: "#f7fee7", avatarColor: "#65a30d", pill: "#65a30d", bg: "#f7fee7", text: "#65a30d", border: "#d9f99d" },
};

export const ARTICLES = [
  // ── AI ──────────────────────────────────────────────────────────────────────
  {
    id: 1,
    catKey: "ai",
    cat: "AI",
    title: "How Prompt Engineering Is Becoming the Most Valuable Skill of the Decade",
    shortDesc: "The people who know how to talk to AI systems effectively will have an outsized advantage in every profession. Here's how to build that skill.",
    fullDesc: "Prompt engineering is rapidly emerging as the defining skill of the AI era. Unlike traditional coding, it requires no syntax memorisation — but it demands a deep understanding of how large language models reason, where they fail, and how to structure requests to get consistently useful outputs. This article breaks down the core principles of effective prompting, shares advanced techniques used by AI researchers, and gives you a practical framework to apply immediately in your work.",
    tags: ["Prompt Engineering", "AI Skills", "Future of Work"],
    author: "Arjun Mehta",
    initials: "AM",
    authorRole: "AI Research Lead, DeepMind India",
    authorBio: "Arjun leads applied AI research at DeepMind's India operations. He has published 14 papers on language model alignment and teaches prompt design workshops to enterprise teams across Asia.",
    readTime: "6 min",
    date: "May 4",
    views: "21.4k",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80",
    trending: true,
    coverImg: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80",
    content: [
      { type: "lead", text: "The people who understand how to communicate with AI systems effectively will have a compounding advantage over those who don't. Prompt engineering is not a passing trend — it is the new literacy." },
      { type: "h2", text: "Why Prompting Is Harder Than It Looks" },
      { type: "p", text: "Large language models are trained on vast corpora of human text and are exquisitely sensitive to phrasing, context, and framing. The same question asked in two different ways can produce radically different outputs. Understanding this sensitivity — and using it deliberately — is the core of prompt engineering." },
      { type: "callout", text: "🤖 Key Insight: Studies show that adding the phrase 'think step by step' to a prompt improves accuracy on complex reasoning tasks by up to 40%. The model doesn't change — only the instruction does." },
      { type: "h2", text: "The Five Principles of Effective Prompting" },
      { type: "p", text: "1. Be specific about format — tell the model exactly what structure you want. 2. Provide context and role — 'You are a senior data analyst reviewing...' dramatically changes output quality. 3. Use examples — show the model what good output looks like. 4. Break complex tasks into steps. 5. Iterate — treat the first output as a draft, not a deliverable." },
      { type: "h2", text: "Advanced Techniques: Chain-of-Thought and Self-Critique" },
      { type: "p", text: "Chain-of-thought prompting asks the model to reason through a problem before answering. Self-critique prompting asks it to evaluate and improve its own output. Combined, these techniques produce outputs that rival expert human work on many structured tasks." },
      { type: "quote", text: "The best prompt engineers I've worked with don't think of themselves as coders. They think of themselves as communicators who happen to be talking to a very unusual kind of mind.", author: "Arjun Mehta, DeepMind India" },
      { type: "h2", text: "Where to Start" },
      { type: "p", text: "Pick one task you do repeatedly — summarising reports, writing emails, analysing data. Spend one hour this week writing and refining a prompt for that task. Document what works. Within two weeks, you will have a personal prompt library that saves hours monthly and produces better output than generic queries ever could." },
    ],
    relatedIds: [9],
  },
  {
    id: 2,
    catKey: "ai",
    cat: "AI",
    title: "Using AI to Personalise Learning at Scale: What Educators Need to Know",
    shortDesc: "Adaptive AI tutors are outperforming one-size-fits-all curricula. Here's what the research says and how trainers can adapt.",
    fullDesc: "AI-powered adaptive learning platforms are transforming education by tailoring content, pacing, and feedback to each individual learner in real time. This has profound implications for corporate trainers, educators, and coaches who previously had no way to personalise at scale. This article explores the evidence, the leading platforms, and practical steps for integrating AI-driven personalisation into any training programme.",
    tags: ["EdTech", "Adaptive Learning", "AI Tools"],
    author: "Priya Nair",
    initials: "PN",
    authorRole: "Learning Experience Designer, Coursera",
    authorBio: "Priya designs AI-powered learning experiences for Coursera's enterprise clients. She has a PhD in Educational Psychology from IIT Bombay and has helped over 200 organisations redesign their training programmes.",
    readTime: "5 min",
    date: "May 2",
    views: "9.7k",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80",
    content: [
      { type: "lead", text: "One-size-fits-all training fails most learners. AI-powered personalisation solves this at a scale that no human facilitator can match — if you implement it correctly." },
      { type: "h2", text: "How Adaptive Learning Works" },
      { type: "p", text: "Adaptive learning systems use machine learning models trained on learner performance data to dynamically adjust content difficulty, sequence, and modality. When a learner struggles with a concept, the system offers additional explanations, worked examples, or analogies. When they excel, it accelerates progression or introduces extensions." },
      { type: "callout", text: "📈 Research: A 2024 meta-analysis of 62 studies found that adaptive AI tutoring systems produced learning gains equivalent to human one-on-one tutoring in 78% of evaluated domains." },
      { type: "h2", text: "Leading Platforms and Their Strengths" },
      { type: "p", text: "Khanmigo (Khan Academy's AI tutor) excels at Socratic dialogue. Duolingo's AI engine personalises language learning through spaced repetition and difficulty modulation. For corporate training, Docebo, 360Learning, and Degreed all have robust AI personalisation features. At the frontier, Carnegie Learning's MATHia uses decades of cognitive science research to power its adaptive mathematics platform." },
      { type: "quote", text: "The question for trainers is no longer whether AI can personalise learning — it clearly can. The question is whether trainers will redesign their programmes to take advantage of it.", author: "Priya Nair, Coursera" },
      { type: "h2", text: "Getting Started as a Trainer" },
      { type: "p", text: "Start by mapping your content to clear learning objectives and competency levels. Most AI platforms need well-structured content to personalise effectively — uploading a flat document won't work. Tag each piece of content with the concept it covers and the difficulty level. Then choose a platform that matches your budget and learner context, and run a 4-week pilot with a small cohort before scaling." },
    ],
    relatedIds: [1],
  },

  // ── GOAL-BASED ───────────────────────────────────────────────────────────────
  {
    id: 3,
    catKey: "goal",
    cat: "Goal-Based",
    title: "Why Most Goal-Setting Frameworks Fail — And What Actually Works",
    shortDesc: "OKRs, SMART goals, vision boards — most people try them all and abandon them all. The science points to a different approach.",
    fullDesc: "The self-help industry has produced dozens of goal-setting frameworks. Most people have tried several and abandoned most. The problem isn't motivation or discipline — it's that popular frameworks ignore how the brain actually processes and pursues goals. This article reviews the cognitive science of goal pursuit, identifies the critical failures in common frameworks, and presents an evidence-based alternative that dramatically improves follow-through.",
    tags: ["Goal Setting", "Productivity", "Behaviour Change"],
    author: "Dr. Kavita Sharma",
    initials: "KS",
    authorRole: "Behavioural Psychologist & Executive Coach",
    authorBio: "Dr. Sharma is a behavioural psychologist with 16 years of experience coaching C-suite executives across Fortune 500 companies. She holds a PhD from the University of Cambridge and specialises in goal pursuit and behaviour change science.",
    readTime: "7 min",
    date: "Apr 30",
    views: "17.2k",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=1200&q=80",
    trending: true,
    coverImg: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=1200&q=80",
    content: [
      { type: "lead", text: "You've set goals before. You probably didn't achieve most of them. That's not a character flaw — it's a design flaw in how you were taught to set goals. Here's what actually works." },
      { type: "h2", text: "Where SMART Goals Go Wrong" },
      { type: "p", text: "SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound) are structurally sound but psychologically incomplete. They tell you what to aim for but nothing about the identity shifts, environmental design, or implementation intentions required to actually change behaviour. Research by Peter Gollwitzer shows that specificity without implementation planning reduces goal completion — not increases it." },
      { type: "callout", text: "🧠 Science: Mental contrasting — vividly imagining both the desired future AND the specific obstacles between you and it — is 300% more effective than positive visualisation alone. This is called WOOP (Wish, Outcome, Obstacle, Plan)." },
      { type: "h2", text: "The Identity-First Approach" },
      { type: "p", text: "James Clear's research on habit formation and identity change reveals the most durable path to goal achievement: start with who you want to become, not what you want to achieve. Instead of 'I want to publish a book', the identity goal is 'I am a writer who writes 500 words every morning'. Every action then becomes a vote for that identity rather than a step toward an outcome." },
      { type: "h2", text: "Implementation Intentions: The Missing Link" },
      { type: "p", text: "Meta-analyses of over 100 studies show that adding an implementation intention ('I will do X at time Y in location Z') to any goal increases completion rates by 200–300%. The specificity triggers automatic behaviour rather than relying on willpower. Schedule your goal actions into your calendar as non-negotiable appointments." },
      { type: "quote", text: "Every time I work with an executive who is 'failing at goals', I find the same thing: they have outcomes but no systems. Goals tell you where to go; systems determine whether you get there.", author: "Dr. Kavita Sharma" },
      { type: "h2", text: "A Practical Framework That Works" },
      { type: "p", text: "Step 1: Define the identity you're building (not the outcome you want). Step 2: Use WOOP to stress-test it against real obstacles. Step 3: Write implementation intentions for your three most critical actions. Step 4: Design your environment to make the right action the easy action. Step 5: Track leading indicators (actions) not lagging indicators (results) — results lag by weeks or months; actions are immediate feedback." },
    ],
    relatedIds: [6],
  },

  // ── COMMUNICATION ────────────────────────────────────────────────────────────
  {
    id: 4,
    catKey: "communication",
    cat: "Communication",
    title: "The Science of Persuasion: How Top Leaders Communicate to Inspire Action",
    shortDesc: "Effective communicators don't rely on charisma — they follow evidence-based principles that anyone can learn.",
    fullDesc: "Communication is the most leveraged skill in any leader's toolkit. Yet most communication training focuses on presentation mechanics — posture, eye contact, vocal variety — while ignoring the cognitive science of how humans actually process and respond to messages. This article distils 50 years of persuasion research into a practical framework for communicators at every level.",
    tags: ["Persuasion", "Public Speaking", "Influence"],
    author: "Rahul Desai",
    initials: "RD",
    authorRole: "Executive Communication Coach, IIM Ahmedabad",
    authorBio: "Rahul coaches senior leaders at India's top corporations on high-stakes communication. He is an adjunct faculty at IIM Ahmedabad and author of 'The Architecture of Influence', a bestselling communication guide.",
    readTime: "5 min",
    date: "Apr 28",
    views: "13.1k",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80",
    content: [
      { type: "lead", text: "The most influential communicators aren't born — they are built. Every technique they use is learnable, and most are counterintuitive to what communication training has traditionally taught." },
      { type: "h2", text: "Lead With Loss, Not Gain" },
      { type: "p", text: "Kahneman and Tversky's prospect theory demonstrates that losses are psychologically twice as powerful as equivalent gains. Effective communicators frame messages around what the audience stands to lose by not acting, not what they gain by acting. 'This approach will save you ₹50 lakh' is significantly less compelling than 'This approach will stop you losing ₹50 lakh you've already earned'." },
      { type: "callout", text: "💡 Technique: Before any high-stakes communication, write two versions of your core message — one gain-framed, one loss-framed. Test both. Loss-framed messages typically produce 60–80% higher action rates in decision-making contexts." },
      { type: "h2", text: "The Power of Concrete Specificity" },
      { type: "p", text: "Abstract communication creates no mental picture and no emotional response. 'We improved efficiency' produces nothing. 'We reduced the time your team spends on monthly reporting from 14 hours to 3 hours' creates a vivid, emotionally resonant picture. Specificity signals confidence, competence, and credibility simultaneously." },
      { type: "h2", text: "Narrative Structure: Why Stories Work" },
      { type: "p", text: "Neuroscience shows that stories activate the same neural pathways as lived experience — the listener's brain processes a well-told story as if they are experiencing it directly. Structure every important communication as: situation (what was true), complication (what changed), resolution (what you propose). This three-act arc is the most durable persuasive structure in human communication history." },
      { type: "quote", text: "The best communicators I've coached have one thing in common: they are obsessively audience-centric. They never ask 'what do I want to say?' They ask 'what does this specific person need to hear to move?'", author: "Rahul Desai, IIM Ahmedabad" },
      { type: "h2", text: "Listening as a Persuasion Tool" },
      { type: "p", text: "Harvard research on negotiation consistently shows that the person who asks the most questions in a conversation has the most influence over its outcome. Strategic listening — asking questions that help the other person articulate their own concerns — is more persuasive than any argument you can make. When people hear themselves articulate a problem, they are primed to accept solutions." },
    ],
    relatedIds: [7],
  },

  // ── DATA SCIENCE ─────────────────────────────────────────────────────────────
  {
    id: 5,
    catKey: "data",
    cat: "Data Science",
    title: "From Data to Decisions: The Framework Every Analyst Needs",
    shortDesc: "Raw data doesn't drive decisions — the narrative around it does. Here's how to bridge the gap between analysis and action.",
    fullDesc: "Data science has a last-mile problem: the gap between rigorous analysis and organisational action. Most analysts can build models; few can make decision-makers act on them. This article presents a practical framework for translating complex data insights into compelling narratives that drive real business decisions.",
    tags: ["Data Analysis", "Storytelling", "Decision Making"],
    author: "Ananya Krishnan",
    initials: "AK",
    authorRole: "Principal Data Scientist, Flipkart",
    authorBio: "Ananya leads data science at Flipkart's growth division, managing a team of 24 analysts. She has an MS in Statistics from IISc Bangalore and is known for her work bridging data science and business strategy.",
    readTime: "6 min",
    date: "Apr 26",
    views: "10.8k",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    content: [
      { type: "lead", text: "A technically perfect analysis presented poorly changes nothing. The skill gap in data science is not statistical — it's communicative. Here's how to close it." },
      { type: "h2", text: "The Pyramid Principle for Data Storytelling" },
      { type: "p", text: "Barbara Minto's Pyramid Principle — developed at McKinsey — is the most effective structure for presenting data insights to decision-makers. Start with the conclusion (the 'so what'), then provide three supporting arguments, then the supporting data. Never bury the insight in the methodology. Executives have 90 seconds of patience; spend them on your answer, not your approach." },
      { type: "callout", text: "📊 Common Mistake: 94% of analyst presentations lead with methodology ('We analysed 6 months of data using...') instead of insight ('Our highest-value customers are churning because of one specific friction point'). Reverse this. Always." },
      { type: "h2", text: "Making Uncertainty Legible" },
      { type: "p", text: "Non-technical stakeholders find confidence intervals, p-values, and model accuracy metrics confusing and off-putting. Translate statistical uncertainty into business risk: 'Our model is 85% confident' means nothing to a CFO. 'In 15 out of 100 similar situations, this prediction would be wrong — here's what we'd do when that happens' creates actionable understanding." },
      { type: "h2", text: "The Decision-First Framework" },
      { type: "p", text: "Before building any analysis, start with the decision it needs to support. What are the options? What information would change which option is chosen? What is the minimum viable evidence needed to make this call? This reversal — starting with the decision, not the data — prevents analysis paralysis and ensures your work is directly actionable." },
      { type: "quote", text: "The best analysts I've worked with spend as much time designing how they'll present an insight as they spend deriving it. Presentation is not decoration — it is half the analysis.", author: "Ananya Krishnan, Flipkart" },
      { type: "h2", text: "Visualisation Principles That Work" },
      { type: "p", text: "Use the simplest chart type that accurately represents your data. Remove every element that doesn't carry information (chartjunk). Use colour deliberately — one accent colour for what matters, grey for everything else. Label data directly rather than using legends. And always title your chart with the insight, not the description: 'Revenue grew 34% after the price change' instead of 'Monthly Revenue by Period'." },
    ],
    relatedIds: [1],
  },

  // ── LEADERSHIP ───────────────────────────────────────────────────────────────
  {
    id: 6,
    catKey: "leadership",
    cat: "Leadership",
    title: "The Counterintuitive Truth About High-Performance Leadership",
    shortDesc: "The most effective leaders don't push harder — they remove friction. Here's the research behind multiplier leadership.",
    fullDesc: "Leadership development has long focused on developing individual leaders' skills. The research, however, increasingly shows that the most impactful leadership intervention is not developing the leader — it's designing the conditions that allow teams to perform at their ceiling. This article explores multiplier leadership, psychological safety, and the environmental design principles that produce extraordinary team performance.",
    tags: ["Leadership", "High Performance", "Team Design"],
    author: "Vikram Sood",
    initials: "VS",
    authorRole: "Organisational Psychologist & Leadership Advisor",
    authorBio: "Vikram advises boards and executive teams on leadership effectiveness at India's fastest-growing companies. He is a former McKinsey partner and visiting faculty at ISB Hyderabad.",
    readTime: "8 min",
    date: "Apr 24",
    views: "15.6k",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    trending: true,
    coverImg: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    content: [
      { type: "lead", text: "The leaders who produce the highest-performing teams are often the quietest in the room. They don't dominate — they create the conditions for others to perform at levels that surprise even themselves." },
      { type: "h2", text: "Multipliers vs. Diminishers" },
      { type: "p", text: "Liz Wiseman's research across 150 leaders in 35 companies found that 'multiplier' leaders — those who amplify the intelligence around them — got 1.97x the output from their teams compared to 'diminisher' leaders of equivalent seniority and technical ability. The difference had nothing to do with technical skill and everything to do with how they used the intelligence in the room." },
      { type: "callout", text: "🔬 Research Finding: Multiplier leaders ask questions 4x more than they make statements. They credit others publicly and challenge them privately. They hold high standards but assume positive intent and capability." },
      { type: "h2", text: "Psychological Safety: The Prerequisite" },
      { type: "p", text: "Google's Project Aristotle — a 5-year study of 180 teams — found that psychological safety was the single strongest predictor of team performance, more predictive than individual talent, team composition, or leadership seniority. Psychological safety is not comfort or niceness — it is the belief that one can take risks, share unpopular views, and make mistakes without fear of humiliation or punishment." },
      { type: "h2", text: "The Three Questions That Change Team Culture" },
      { type: "p", text: "Ask these consistently in team settings: 'What do you think?' (signals you value their input), 'What are we missing?' (normalises uncertainty and invites dissent), 'What would you do?' (develops ownership and decision-making capability). Leaders who ask these three questions habitually build teams that are dramatically more autonomous, innovative, and resilient than those who default to telling." },
      { type: "quote", text: "The hardest leadership skill to develop is restraint. Knowing when not to speak, when not to solve, when not to direct — and trusting that your team will figure it out, and grow because they did.", author: "Vikram Sood" },
      { type: "h2", text: "Designing for Performance" },
      { type: "p", text: "Environmental design — the structure of meetings, communication channels, decision rights, and feedback loops — shapes behaviour more powerfully than any training intervention. Audit your team's operating rhythm: Are decisions being made at the right level? Do people have the information they need when they need it? Is there a structured way to surface and learn from failures? Fix the system before coaching the people." },
    ],
    relatedIds: [7, 3],
  },

  // ── MANAGEMENT ───────────────────────────────────────────────────────────────
  {
    id: 7,
    catKey: "management",
    cat: "Management",
    title: "The Manager's Most Powerful Tool: The Weekly One-on-One",
    shortDesc: "Most managers run one-on-ones wrong — and it's costing them team performance, retention, and their own time.",
    fullDesc: "The weekly one-on-one is the highest-leverage management activity available. Done well, it surfaces problems before they become crises, builds trust that improves team performance across every dimension, and is the primary vehicle through which great managers develop people. Done poorly, it is a status update meeting that wastes 30 minutes for both parties. This article explains exactly how to run one-on-ones that transform your team.",
    tags: ["Management", "One-on-One", "Team Development"],
    author: "Sneha Kapoor",
    initials: "SK",
    authorRole: "Head of People Development, Zomato",
    authorBio: "Sneha leads management development at Zomato, having built the people management capability across 800+ managers over six years. She is certified by the Co-Active Training Institute and coaches startup founders and senior managers.",
    readTime: "6 min",
    date: "Apr 22",
    views: "11.3k",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&q=80",
    content: [
      { type: "lead", text: "The quality of your one-on-ones is the best single predictor of your team's performance, retention, and engagement. Most managers run them wrong. Here's how to fix that — starting this week." },
      { type: "h2", text: "The Purpose of a One-on-One" },
      { type: "p", text: "A one-on-one is not a status update. Status updates should happen asynchronously. The one-on-one has three distinct purposes: (1) to surface what the manager cannot see from a distance — blockers, frustrations, and context that don't reach them through formal channels; (2) to invest in the person's development; (3) to build the trust that makes everything else in the working relationship function better." },
      { type: "callout", text: "📋 Rule: 90% of the talking in a one-on-one should be done by the team member. If you're talking more than 10% of the time, you've converted it into a briefing session — and you've lost the meeting's primary value." },
      { type: "h2", text: "A Framework That Works" },
      { type: "p", text: "Use three consistent questions to structure every meeting: 'What's going well that I should know about?' (surfaces wins, builds confidence, gives you signal on what to reinforce). 'What's most frustrating or stuck right now?' (surfaces blockers early, when they're still small). 'What do you need from me this week?' (builds accountability and makes your support explicit rather than assumed)." },
      { type: "h2", text: "The 15-Minute Protocol" },
      { type: "p", text: "Great one-on-ones do not require an hour. A tightly run 25-minute cadence — 5 minutes of open space for the team member to lead, 10 minutes on current work and blockers, 10 minutes on development — is more valuable than an hour-long meeting with no structure. The cadence matters more than the duration: weekly beats bi-weekly, bi-weekly beats monthly." },
      { type: "quote", text: "I inherited a team with 40% attrition. The single change that moved the needle most was fixing our one-on-ones. Within six months, attrition dropped to 12%. People don't leave companies — they leave managers who don't see them.", author: "Sneha Kapoor, Zomato" },
      { type: "h2", text: "Common Mistakes to Avoid" },
      { type: "p", text: "Cancelling repeatedly signals your team member is not a priority — the trust cost is enormous. Turning it into a task-tracking session wastes its relationship-building value. Skipping development conversations because there's 'always something urgent' ensures your team never grows. And failing to take notes means patterns go unnoticed and commitments forgotten. Note three things at every meeting: what they said, what you committed to, and what they committed to." },
    ],
    relatedIds: [6],
  },

  // ── SOFT SKILLS ──────────────────────────────────────────────────────────────
  {
    id: 8,
    catKey: "softskills",
    cat: "Soft Skills",
    title: "Emotional Intelligence Is Not Soft — It's Your Most Marketable Skill",
    shortDesc: "In an era of AI automation, EQ is becoming the hardest-to-replace and highest-valued competency in every industry.",
    fullDesc: "As AI systems take over an expanding range of cognitive tasks, the distinctly human skills of emotional regulation, empathy, and social intuition are becoming the competitive differentiator in virtually every professional domain. This article reframes emotional intelligence as a hard, learnable, and critical business skill — and gives you a practical development path.",
    tags: ["Emotional Intelligence", "EQ", "Future Skills"],
    author: "Dr. Meera Pillai",
    initials: "MP",
    authorRole: "Organisational Psychologist & EQ Trainer",
    authorBio: "Dr. Pillai is an organisational psychologist and certified EQ-i 2.0 coach with 13 years of experience developing emotional intelligence in leaders and teams across 40 organisations in India, Singapore, and the UAE.",
    readTime: "5 min",
    date: "Apr 20",
    views: "14.9k",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=1200&q=80",
    content: [
      { type: "lead", text: "The World Economic Forum's Future of Jobs Report consistently ranks emotional intelligence in the top five most in-demand skills globally. It's not a personality trait — it's a skill set with a clear development pathway." },
      { type: "h2", text: "What EQ Actually Is" },
      { type: "p", text: "Daniel Goleman's original model defines EQ across five domains: self-awareness (knowing your own emotions), self-regulation (managing your emotional responses), motivation (directing emotions toward goals), empathy (reading others' emotions accurately), and social skills (managing relationships effectively). Most people are strong in one or two and weak in others — and those weak areas are where careers stall." },
      { type: "callout", text: "🌟 Career Impact: TalentSmart research across 500,000 professionals found that EQ accounts for 58% of performance across all job types. Professionals with high EQ earn an average of $29,000 more annually than their low-EQ peers in equivalent roles." },
      { type: "h2", text: "The Most Developable Component: Self-Regulation" },
      { type: "p", text: "Self-regulation — the ability to choose your response to an emotional trigger rather than react automatically — is the highest-leverage EQ skill for most professionals. The physiological gap between stimulus and response is approximately 90 seconds: research by neuroscientist Jill Bolte Taylor shows that the biochemical surge of an emotion peaks and dissolves within 90 seconds without active mental reinforcement. Developing a 90-second pause practice is the foundation of self-regulation." },
      { type: "h2", text: "Empathy Is a Skill, Not a Personality Trait" },
      { type: "p", text: "Cognitive empathy — the ability to accurately understand another person's perspective and emotional state — is a learnable, practicable skill. The most effective development method: before any important conversation, spend 2 minutes writing down how the other person likely feels about the situation, what their main concerns are, and what they need from this interaction. This deliberate perspective-taking activates the same neural networks as natural empathy and produces dramatically better relationship outcomes." },
      { type: "quote", text: "Every difficult colleague I've ever worked with became dramatically easier to work with the moment I genuinely understood what they were afraid of. EQ is not about being nicer. It's about being smarter about human beings.", author: "Dr. Meera Pillai" },
      { type: "h2", text: "A 30-Day EQ Development Protocol" },
      { type: "p", text: "Week 1: Daily emotion labelling — at three points in the day, name the emotion you're experiencing and its intensity on a 1–10 scale. This builds self-awareness. Week 2: Trigger mapping — identify the three situations that most reliably produce unhelpful emotional reactions. Week 3: Response planning — for each trigger, design the response you want to have instead. Week 4: Social experimentation — apply deliberate empathy to two interactions daily and observe the difference in outcomes." },
    ],
    relatedIds: [4],
  },

  // ── TECHNICAL ────────────────────────────────────────────────────────────────
  {
    id: 9,
    catKey: "technical",
    cat: "Technical",
    title: "System Design Mastery: How to Think in Distributed Systems",
    shortDesc: "The gap between a good engineer and a great one is rarely algorithmic — it's architectural. Here's how to develop systems thinking.",
    fullDesc: "System design is the discipline that separates engineers who build features from engineers who build platforms. As software systems scale, the challenges shift from algorithmic correctness to distributed coordination, fault tolerance, and operational complexity. This article builds an intuition for system design that serves across every domain of software engineering.",
    tags: ["System Design", "Architecture", "Engineering"],
    author: "Rohit Bose",
    initials: "RB",
    authorRole: "Staff Engineer, Google",
    authorBio: "Rohit is a staff engineer at Google's infrastructure division with 12 years of experience building distributed systems at scale. He mentors engineers preparing for senior and staff-level roles and writes extensively on systems thinking.",
    readTime: "9 min",
    date: "Apr 18",
    views: "18.4k",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80",
    trending: true,
    coverImg: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80",
    content: [
      { type: "lead", text: "System design is not a set of patterns to memorise — it's a way of thinking. The best distributed systems engineers share a mental model of how components fail, scale, and interact that transcends any specific technology or framework." },
      { type: "h2", text: "Start With Constraints, Not Solutions" },
      { type: "p", text: "The most common system design mistake: jumping to solutions before understanding constraints. Before proposing any architecture, establish: What is the read/write ratio? What are the consistency requirements (can we tolerate stale reads)? What is the expected scale (users, requests per second, data volume)? What are the latency requirements? These constraints determine your architecture — not the other way around." },
      { type: "callout", text: "⚙️ Engineering Principle: CAP Theorem states that a distributed system can provide at most two of three guarantees: Consistency, Availability, and Partition Tolerance. Knowing which two your system prioritises is the first architectural decision — and it shapes every subsequent one." },
      { type: "h2", text: "The Components Every System Needs" },
      { type: "p", text: "Every scalable system resolves around the same core components: a load balancer to distribute traffic, a CDN for static asset delivery and geographic distribution, an application layer (stateless for horizontal scaling), a caching layer (Redis or Memcached) to absorb read load, a primary database with read replicas, and an async message queue (Kafka, SQS) for decoupled processing. Understanding when to add each component — and why — is the essence of system design." },
      { type: "h2", text: "Designing for Failure" },
      { type: "p", text: "At scale, failure is not an edge case — it is the baseline condition. Design every component with its failure mode in mind: What happens when this service is unavailable? How does the system degrade gracefully rather than fail catastrophically? Circuit breakers, bulkheads, timeouts, retries with exponential backoff, and dead letter queues are not optimisations — they are fundamental design requirements for any production system." },
      { type: "quote", text: "I ask every engineer I interview one question: 'How does your favourite system fail?' The engineers who can answer this in detail are the ones I want designing systems. Building for the happy path is easy. Building for reality is engineering.", author: "Rohit Bose, Google" },
      { type: "h2", text: "How to Develop Systems Thinking" },
      { type: "p", text: "Three practices that compound: (1) Read post-mortems — Google, Netflix, Cloudflare, and Stripe all publish detailed incident analyses. These are the best systems education available. (2) Draw every system you work on — whiteboard the data flow, identify the bottlenecks, ask what breaks first at 10x scale. (3) Practice estimations — back-of-envelope calculations (QPS, storage, bandwidth) build the numerical intuition that separates architectural clarity from hand-waving." },
    ],
    relatedIds: [1],
  },

  // ── WELLNESS ─────────────────────────────────────────────────────────────────
  {
    id: 10,
    catKey: "wellness",
    cat: "Wellness",
    title: "The Science of Sustainable High Performance Without Burnout",
    shortDesc: "Burnout is not a badge of honour — it's an operational failure. Here's what neuroscience says about performing at your peak indefinitely.",
    fullDesc: "The performance paradox: the harder you push without strategic recovery, the worse your performance becomes — and the slower you're able to recover. Burnout is not a sudden event; it's the outcome of a long, measurable process that can be interrupted at multiple points. This article presents the neuroscience of sustainable performance and a practical protocol for performing at your peak without destroying your capacity to do so in the future.",
    tags: ["Burnout Prevention", "High Performance", "Recovery"],
    author: "Dr. Aditi Rao",
    initials: "AR",
    authorRole: "Performance Neuroscientist & Wellness Coach",
    authorBio: "Dr. Rao is a neuroscientist and certified wellness coach who has worked with Olympic athletes, startup founders, and senior executives. She completed her post-doctoral research at NIMHANS and runs a performance wellness clinic in Bangalore.",
    readTime: "7 min",
    date: "Apr 15",
    views: "16.2k",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
    trending: false,
    coverImg: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
    content: [
      { type: "lead", text: "Burnout doesn't happen suddenly. It accumulates over months of ignoring signals your nervous system was sending clearly. The good news: those signals are legible, and the intervention is earlier than you think." },
      { type: "h2", text: "What Burnout Actually Is Neurologically" },
      { type: "p", text: "Burnout is characterised by chronic depletion of three neurotransmitter systems: dopamine (motivation and drive), norepinephrine (focus and attention), and serotonin (mood regulation and resilience). This depletion doesn't happen overnight — it's the cumulative result of sustained demands without adequate recovery. The prefrontal cortex — the brain's executive centre — progressively loses function, making tasks that were once manageable feel overwhelming." },
      { type: "callout", text: "🧘 Early Warning Signals: Difficulty starting tasks (not finishing them), increased emotional reactivity over small setbacks, reduced enjoyment of activities previously found rewarding, and sleep that doesn't feel restorative. These appear 4–8 weeks before full burnout." },
      { type: "h2", text: "The 90-Minute Performance Cycle" },
      { type: "p", text: "Ultradian rhythms — 90-minute biological cycles that govern alertness and focus — are the foundation of sustainable performance. Research by Peretz Lavie and Nathaniel Kleitman shows that our brains cycle between high-alertness and low-alertness states every 90 minutes throughout the day. Working with this rhythm — intense focus for 90 minutes, genuine 20-minute recovery, repeat — produces dramatically more output than 8 continuous hours of diminishing returns." },
      { type: "h2", text: "The Recovery Protocol" },
      { type: "p", text: "Recovery is active, not passive. True cognitive recovery requires complete disengagement from work-related thought: nature walks (shown to reduce prefrontal activity), non-sleep deep rest (NSDR/Yoga Nidra), deliberate play with no productivity objective, physical exercise (the most potent neurochemical reset available), and social connection. Scrolling social media during 'breaks' maintains cognitive load and provides no recovery benefit." },
      { type: "quote", text: "Every elite performer I've worked with has a deliberate recovery protocol as non-negotiable as their performance protocol. They understand something that most professionals learn too late: recovery is not the absence of work. It is the precondition of it.", author: "Dr. Aditi Rao" },
      { type: "h2", text: "The Minimum Effective Dose of Recovery" },
      { type: "p", text: "You don't need a retreat or a sabbatical to restore performance capacity. The minimum effective protocol: 7–9 hours of sleep (non-negotiable), one genuinely unplugged 24-hour period per week, 20 minutes of zone-2 cardio 3x per week, and a deliberate end-of-workday transition ritual that signals to your nervous system that performance mode is over. These four inputs, consistently applied, prevent 80% of performance-related burnout." },
    ],
    relatedIds: [3],
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function makeSlug(article) {
  const slug = article.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60);
  return `${article.id}-${slug}`;
}

export function findArticle(idOrSlug) {
  const byId = ARTICLES.find((a) => String(a.id) === String(idOrSlug));
  if (byId) return byId;
  const match = String(idOrSlug).match(/^(\d+)-/);
  if (match) return ARTICLES.find((a) => a.id === Number(match[1]));
  return null;
}

export function getRelated(article) {
  const ids = article.relatedIds || [];
  const byCat = ARTICLES.filter(
    (a) => a.id !== article.id && a.catKey === article.catKey && !ids.includes(a.id)
  );
  const byId = ids.map((id) => ARTICLES.find((a) => a.id === id)).filter(Boolean);
  return [...byId, ...byCat].slice(0, 3);
}